### ISSUE TITLE
[Feat] 1차 세미나 과제

### ISSUE THREAD

**Issue by joho2022** [AND-SOPT-iOS/JoHoGeun#1]
## 📌 Issue

최종결과물을 바탕으로 과제 진행

## 📋 To-do List
- [x] UI Component 다루지 않은 속성 추가
- [x] UI Component 추가
- [x] Auto Layout 적용
