### ISSUE TITLE
[Feat] 2차 세미나 과제

### ISSUE THREAD

**Issue by joho2022** [AND-SOPT-iOS/JoHoGeun#3]
## 📌 Issue

토스앱스토어 상세 페이지 구현

## 📋 To-do List
- [x] 컴포넌트 배치 위주로 구현 목표 (열기, 공유 X)
- [x] person이모지로 대체
- [x] 버전기록 버튼 탭할 때, 버전기록 뷰 이동만 하도록 연결
- [x] 미리보기에는 이미지 하나만 나오도록 구현
- [x] 평가 및 리뷰 모두 보기 탭할 때, 모두 보기 뷰로 이동만 하도록 연결
